version: "3.8"
services:
  node:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - "home/app/node_modules"
      - "./:/home/app"